README.md

Not sure if you want to start adding github links to projects, but i feel like most people would find them useful. In this instance, its still just a stub repo, but its from the official authors.

Added github link to GRF

---

README.md
citations/d-nerf2.txt

Hello,
Thank you for creating this repo. I have added to the list our new arxiv that just came out today.
https://www.albertpumarola.com/research/D-NeRF/index.html
Thank you,
Albert

Request to add new paper

---

README.md
citations/neuralbody.txt

Hi,
Neural Body improves neural radiance fields using structured latent codes.
It would be great if you added [Neural Body: Implicit Neural Representations with Structured Latent Codes for Novel View Synthesis of Dynamic Humans](https://arxiv.org/abs/2012.15838).
Best,
Sida

add Neural Body.

---

README.md

change the link of AutoInt from arxiv to its project page

Change AutoInt link

---

README.md

[A-NeRF: Surface-free Human 3D Pose Refinement via Neural Rendering](https://lemonatsu.github.io/ANeRF-Surface-free-Pose-Refinement/)
by  _Shih-Yang Su_, _Frank Yu_, _Michael Zollhoefer_, _Helge Rhodin_.
A novel test-time optimization approach for monocular motion capture that learns a volumetric body model of the user in a self-supervised manner.

Add A-NeRF

---

README.md

Added link in the "implementation" section, but I'd like it to be next to the paper Nerf-W for more visibility...
Experiments on real data and lego have been successfully trained and tested.
For details, please see #24

Add my implementation of NeRF in the wild (NeRF-W)

---

NeRF-and-Beyond.bib
README.md

Added Neural Scene Graphs Project Page

---

README.md
citations/donerf.txt

Added DONeRF project page and bibtex.

---

README.md
citations/nex.txt

Add Nex: Real-time View Synthesis with Neural Basis Expansion.

---

README.md
citations/semantic-nerf.txt

Add semantic-NeRF. Fix format of NeRD.

Add Semantic-NeRF

---

README.md
citations/fastnerf.txt

add fastnerf

---

README.md

Added Pytorch3D implementation by facebook

---

README.md
citations/nerf-vae.txt

Add NeRF-VAE

---

README.md

add github link for "NeX" paper

---

README.md
citations/narf.txt

add NARF paper

---

README.md

add github link for "IBRNet"

---

README.md

add github link for "nerf--"

---

README.md
citations/editnerf.txt

Edit the shape and color of 3D regions with simple user scribbles.

Add a section on editing and editnerf. 

---

README.md
citations/fig-nerf.txt

Add fignerf

---

README.md
citations/nerfactor.txt

add nerfactor

---

README.md
citations/mipnerf.txt

Add mip-NeRF JAX Implementation

---

README.md
citations/animatable_nerf.txt
citations/neuralbody.txt

Add Animatable NeRF

---

README.md
citations/hypernerf.txt

[HyperNeRF: A Higher-Dimensional Representation for Topologically Varying Neural Radiance Fields](https://hypernerf.github.io/)
by _Keunhong Park_, _Utkarsh Sinha_, _Peter Hedman_, _Jonathan T. Barron_, _Sofien Bouaziz_, _Dan B Goldman_, _Ricardo Martin-Brualla_, _Steven M. Seitz_
> HyperNeRF represents changes in scene topology by providing a NeRF with a higher-dimensional input.

Add HyperNeRF

---

README.md
citations/gnerf.txt
citations/mvsnerf.txt

Add MVSNeRF and GNeRF

---

README.md
citations/anim_nerf.txt

add Chen et al. "Animatable Neural Radiance Fields from Monocular RGB Videos"

---

README.md

add github link for AutoInt & KiloNeRF

---

README.md
citations/barf.txt
citations/dvs_dmv.txt
citations/lfn.txt
citations/nerf-tex.txt
citations/neuray.txt
citations/srf.txt
citations/st-nerf.txt
citations/unisurf.txt
citations/uorf.txt

Works:
- BARF: Bundle-Adjusting Neural Radiance Fields
- Dynamic View Synthesis from Dynamic Monocular Video
- Light Field Networks: Neural Scene Representations with Single-Evaluation Rendering
- NeRF-Tex: Neural Reflectance Field Textures
- Neural Rays for Occlusion-aware Image-based Rendering
- SRF (Stereo Radiance Fields (SRF): Learning View Synthesis from Sparse Views of Novel Scenes)
- ST-NeRF (Editable free-viewpoint video using a layered neural representation)
- UNISURF: Unifying Neural Implicit Surfaces and Radiance Fields for Multi-View Reconstruction
- UORF (Unsupervised Discovery of Object Radiance Fields)
Category:
- Model Reconstruction

Add a few works and a category of Model Reconstruction

---

README.md
citations/DirectVoxGO.txt

Add DirectVoxGO

---

README.md

Update README.md of Ha-NeRF

---

README.md
citations/volsdf.txt

Add "VolSDF".

---

README.md
citations/nerf-dy.txt
citations/vision-only.txt

1. Vision-Only Robot Navigation in a Neural Radiance World
2. 3D Neural Scene Representations for Visuomotor Control

Add two robotics works

---

README.md
citations/3d-video.txt
citations/animatable_nerf.txt

Update some code and papers info for Faster Inference, Deformable and Video.

Update some code and papers info.

---

README.md
citations/nerf-in.txt

NeRF-In is a framework that enables users to remove unwanted objects or retouch undesired regions in a 3D scene represented by a pre-trained NeRF without any category-specific data and training.

add nerf-in

---

README.md
citations/Point-NeRF.txt

Adding Point-NeRF article to the list

---

README.md
citations/mofaNeRF.txt

add mofanerf

---

README.md
citations/NeuralTransmittance
citations/NeuralTransmittance.txt

Neural Transmittance added

---

README.md
citations/mip-nerf-360.txt

- [Mip-NeRF 360: Unbounded Anti-Aliased Neural Radiance Fields](https://jonbarron.info/mipnerf360/), Barron et al., Arxiv 2022 | [bibtex](./citations/mip-nerf-360.txt)
- [Nerual-Radiance-Fields](https://www.kaggle.com/code/ritzraha/nerual-radiance-fields), [@ariG23498](https://twitter.com/ariG23498), [@ritwik_raha](https://twitter.com/ritwik_raha), 2022
- [[Jax + Flax] Minimal Implementation of …

Added Mip-NeRF 360 + More NeRF implementations

---

citations/UV-Volumes.txt

Create UV-Volumes bibtex

---

README.md
citations/StreamRF.txt

add StreamRF from NeurIPS2022

---

README.md
citations/instant-ngp.txt
citations/plenoxels.txt
citations/tensorf.txt

add instant-ngp

---

README.md

add toogle button to all topics

---

README.md
citations/AligNeRF.txt
citations/INS.txt
citations/NeRF-SOS.txt
citations/SinNeRF.txt

Add SinNeRF, INS, NeRF-SOS, AligNeRF to the README

Add SinNeRF, INS, NeRF-SOS, AligNeRF

---

README.md
citations/bakedsdf.txt

Add BakedSDF

---

README.md
citations/Switch-NeRF.txt

1. Put the bibtex in `awesome-NeRF/citations/Switch-NeRF.txt`.
2. Modify the README, add a subcategory of Large-scale scene
3. Modify the README, add details of Switch-NeRF

add a subcategory of Large-scale scene, add Switch-NeRF

---

README.md
citations/neat.txt

Update cvpr2034 paper NeAT

---

README.md
citations/hw_accelaration.txt

This pull request is for a paper recently accepted into ISCA 2023.

HW accelaration ISCA 2023

---

README.md
citations/TiNeuVox.txt

add time aware neural voxels paper

---

README.md
citations/locnerf.txt

adding Loc-NeRF

---

README.md
citations/nerf3dsurvey.txt

Added new survey

---

README.md
citations/BeyondPixels.txt

added a new paper

---

README.md
citations/instantpose.txt

1. Put the BibTeX in `awesome-NeRF/citations/instantpose.txt`.
2. Modified the README accordingly.

Add InstantPose (ICML 2023) paper

---

README.md
citations/hdr-plenoxels.txt

1. Put the bibtex in `awesome-NeRF/citations/hdr-plenoxels.txt`.
2. Modify the README accordingly.

Add hdr-plenoxels (ECCV 2022) paper

---

README.md
citations/Neural-Gauge-Fields.txt

Adding Neural Gauge Fields

---

citations/dylin.txt

add DyLiN paper (cvpr 2023)

---

README.md
citations/neo360.txt

add Neo 360, ICCV'23 

---

README.md
citations/colf.txt
citations/dano.txt
citations/osf.txt
citations/uorf.txt

Update uORF bib (ICLR 2022), add COLF (TMLR 2023)/OSF (TMLR 2023)/DANO (RA-L 2023)

Update uORF bib (ICLR 2022), add COLF (TMLR 2023)/OSF (TMLR 2023)/DANO (RA-L 2023)

---

README.md
citations/contrastive-lift.txt

Add Contrastive-Lift (NeurIPS 2023 Spotlight)

---

README.md
citations/upnerf.txt

Adding UP-NeRF

---

NeRF-and-Beyond.bib
README.md
citations/bundlesdf.txt

Hi, I added this work BundleSDF. Hope this would help the readers. Thank you!

add bundlesdf

---

README.md
citations/uforecon.txt

add UFORecon (CVPR 2024)

---

README.md
citations/lightning-nerf.txt

add Lightning NeRF (ICRA 2024)

---

README.md
citations/KYN.txt

Add Know-Your-Neighbors (KYN, CVPR'2024)

---

README.md
citations/nerf-mae.txt

add NeRF-MAE, ECCV'24 

---

README.md
citations/survey_semantically-awareNeRFs.txt

Adding the Survey: Semantically Aware NeRFs 2024
